//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCommandBarCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomCommandBarCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:frmwrk=&quot;Corel Framework Data&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///&lt;frmwrk:uiconfig&gt;
        ///		&lt;frmwrk:applicationInfo userConfiguration=&quot;true&quot; /&gt;
        ///	&lt;/frmwrk:uiconfig&gt;
        ///	&lt;xsl:template match=&quot;node()|@*&quot;&gt;
        ///		&lt;xsl:copy&gt;
        ///			&lt;xsl:apply-templates select=&quot;node()|@*&quot;/&gt;
        ///		&lt;/xsl:copy&gt;
        ///	&lt;/xsl:template&gt;
        ///
        ///	&lt;xsl:template match=&quot;uiConfig/items&quot;&gt;
        ///		&lt;xsl:copy&gt;
        ///			&lt;xsl:apply-templates select=&quot;node()|@*&quot;/&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppUI {
            get {
                return ResourceManager.GetString("AppUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 17
        ///VisualStudioVersion = 17.6.33723.286
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;$ProjectName$&quot;, &quot;GMSLoader\GMSLoader.csproj&quot;, &quot;{8CD4556C-95AF-423F-B5EA-F87E061163FD}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		2017 Debug|Any CPU = 2017 Debug|Any CPU
        ///		2017 Release|Any CPU = 2017 Release|Any CPU
        ///		2018 Debug|Any CPU = 2018 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GMSLoader {
            get {
                object obj = ResourceManager.GetObject("GMSLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconGroup104 {
            get {
                object obj = ResourceManager.GetObject("IconGroup104", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IconsResources {
            get {
                object obj = ResourceManager.GetObject("IconsResources", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MSBuildLogger {
            get {
                object obj = ResourceManager.GetObject("MSBuildLogger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectHelper {
            get {
                object obj = ResourceManager.GetObject("ProjectHelper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SetupCreator {
            get {
                object obj = ResourceManager.GetObject("SetupCreator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///								xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///								xmlns:frmwrk=&quot;Corel Framework Data&quot;
        ///								exclude-result-prefixes=&quot;frmwrk&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;frmwrk:uiconfig&gt;
        ///    &lt;frmwrk:compositeNode xPath=&quot;/uiConfig/commandBars/commandBarData[@guid=&apos;c2b44f69-6dec-444e-a37e-5dbf7ff43dae&apos;]&quot;/&gt;
        ///	  &lt;frmwrk:compositeNode xPath=&quot;/uiConfig/views/viewTemplate[@guid=&apos;ab303a90-464d-5191-423f-613c4d1dcb2c&apos;]&quot;/&gt;
        ///    &lt;frmw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserUI {
            get {
                return ResourceManager.GetString("UserUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vestris_ResourceLib {
            get {
                object obj = ResourceManager.GetObject("Vestris_ResourceLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
